Repository SFTtech/openage, pull requests merged in 2018-09, with the labels that each got.

#1044 doc: add proton/steam play as a way to obtain assets
  doc/media_convert.md
Labels: documentation, improvement

#1047 Try to use Steam path.
  copying.md
  openage/convert/main.py
Labels: assets, improvement, python

#1049 Fix codegen error during cmake/configure phase
  openage/codegen/codegen.py
Labels: bugfix, buildsystem, python
