Repository SFTtech/openage, pull requests merged in 2018-06, with the labels that each got.

#982 Fixed tests on VS2017
  libopenage/CMakeLists.txt
  libopenage/log/stdout_logsink.cpp
  libopenage/log/stdout_logsink.h
  libopenage/util/compiler.cpp
  libopenage/util/misc.h
Labels: c++, improvement, windows

#1025 [WIP] Lazy Log Message Formatting
  .gitignore
  openage/__init__.py
  openage/__main__.py
  openage/cabextract/cab.py
  openage/codegen/codegen.py
  openage/convert/blendomatic.py
  openage/convert/changelog.py
  openage/convert/colortable.py
  openage/convert/dataformat/content_snippet.py
  openage/convert/driver.py
  openage/convert/drs.py
  openage/convert/gamedata/empiresdat.py
  openage/convert/hdlanguagefile.py
  openage/convert/main.py
  openage/convert/opus/demo.py
  openage/convert/opus/opusenc.pyx
  openage/convert/singlefile.py
  openage/convert/slp.pyx
  openage/convert/slp_converter_pool.py
  openage/convert/texture.py
  openage/cvar/config_file.py
  openage/game/main.py
  openage/log/CMakeLists.txt
  openage/log/__init__.py
  openage/log/log_cpp.pyx
  openage/log/logging.py
  openage/log/tests.py
Labels: improvement, python

#1029 Lazy Log Message Formatting (C++ Side)
  libopenage/log/log.cpp
  libopenage/log/logsink.cpp
  libopenage/log/logsink.h
  libopenage/log/logsource.cpp
  libopenage/log/message.h
  libopenage/util/stringformatter.h
Labels: c++, improvement

#1020 Fix some typos in the documentation
  copying.md
  doc/README.md
  doc/ai/interface.md
  doc/build_instructions/windows_msvc.md
  doc/buildsystem.md
  doc/code/exceptions.md
  doc/code/gui.md
  doc/code/testing.md
  doc/contributing.md
  doc/ideas/editor/README.md
  doc/ideas/gameplay.md
  doc/media/blendomatic.md
  doc/media/original-metadata.md
  doc/media/terrain.md
  doc/reverse_engineering/game_mechanics/attacking_alarm.md
  doc/reverse_engineering/game_mechanics/damage.md
  doc/reverse_engineering/game_mechanics/garrison.md
  doc/reverse_engineering/game_mechanics/market.md
  doc/reverse_engineering/game_mechanics/pathfinding.md
  doc/reverse_engineering/game_mechanics/rates.md
  doc/reverse_engineering/game_mechanics/switching_villager_tasks.md
  doc/reverse_engineering/game_mechanics/town_bell.md
  doc/reverse_engineering/networking/03-sync.md
  doc/reverse_engineering/networking/09-formation.md
  doc/reverse_engineering/scoring.md
Labels: bugfix, documentation

#1032 engine: remove usage of deprecated std::hash::result_type
  libopenage/gamestate/resource.h
  libopenage/gamestate/score.h
  libopenage/unit/ability.h
  libopenage/unit/attribute.h
  libopenage/unit/command.h
Labels: c++, improvement
