Repository SFTtech/openage, pull requests merged in 2018-10, with the labels that each got.

#1056 Remove std::unary_function usage
  libopenage/event/eventqueue.h
Labels: bugfix, c++

#1059 renderer: fix usage of optional and misc
  libopenage/renderer/opengl/buffer.cpp
  libopenage/renderer/opengl/context.cpp
  libopenage/renderer/opengl/context.h
  libopenage/renderer/opengl/framebuffer.cpp
  libopenage/renderer/opengl/geometry.cpp
  libopenage/renderer/opengl/renderer.cpp
  libopenage/renderer/opengl/shader.cpp
  libopenage/renderer/opengl/shader_program.cpp
  libopenage/renderer/opengl/simple_object.cpp
  libopenage/renderer/resources/mesh_data.cpp
  libopenage/renderer/resources/texture_data.cpp
  libopenage/renderer/resources/texture_data.h
  libopenage/renderer/resources/texture_info.cpp
  libopenage/renderer/resources/texture_subinfo.h
  libopenage/renderer/tests.cpp
  libopenage/renderer/text.cpp
  libopenage/renderer/texture.cpp
  libopenage/renderer/texture.h
  libopenage/renderer/texture_array.cpp
  libopenage/renderer/texture_array.h
  libopenage/renderer/window.cpp
  libopenage/renderer/window.h
Labels: bugfix, c++, rendering

#1061 event: remove usage of unistd.h
  libopenage/event/demo/gui.cpp
  libopenage/event/demo/main.cpp
Labels: bugfix, c++, windows
