Repository SFTtech/openage, pull requests merged in 2018-12, with the labels that each got.

#1072 doc: fix table formatting in terrain.md.
  doc/media/terrain.md
Labels: bugfix, documentation

#1073 stemplet-dat.md: add information, clarify int size
  doc/media/stemplet-dat.md
Labels: documentation, improvement

#1045 buildsystem: out of source-tree build
  CMakeLists.txt
  Makefile
  buildsystem/CheckInSourceBuild.cmake
  buildsystem/check_py_file_list.py
  buildsystem/codegen.cmake
  buildsystem/compilepy.py
  buildsystem/cythonize.py
  buildsystem/inplacemodules.py
  buildsystem/pxdgen.py
  buildsystem/python.cmake
  libopenage/CMakeLists.txt
  libopenage/coord/CMakeLists.txt
  libopenage/error/backtrace.cpp
  libopenage/error/stackanalyzer.cpp
  libopenage/event/demo/gamestate.h
  libopenage/event/demo/gui.h
  libopenage/event/demo/main.cpp
  libopenage/event/demo/physics.cpp
  libopenage/log/message.h
  libopenage/testing/.gitignore
  libopenage/testing/testlist.cpp.template
  libopenage/util/externalprofiler.cpp
  libopenage/util/strings.cpp
  libopenage/util/thread_id.cpp
  openage/CMakeLists.txt
  openage/codegen/codegen.py
  openage/codegen/main.py
  openage/convert/dataformat/util.py
Labels: buildsystem, improvement

#1078 renderer: add support for OpenGL uniform blocks in shader_program
  libopenage/renderer/opengl/context.cpp
  libopenage/renderer/opengl/context.h
  libopenage/renderer/opengl/lookup.h
  libopenage/renderer/opengl/shader.cpp
  libopenage/renderer/opengl/shader_program.cpp
  libopenage/renderer/opengl/shader_program.h
  libopenage/renderer/renderer.h
  libopenage/renderer/resources/mesh_data.h
  libopenage/renderer/tests.cpp
Labels: c++, improvement, rendering
