Repository SFTtech/openage, pull requests merged in 2018-11, with the labels that each got.

#1065 convert: fix cythonization for cython 0.29
  buildsystem/cythonize.py
  buildsystem/pxdgen.py
  openage/convert/CMakeLists.txt
  openage/convert/__init__.pxd
  openage/convert/opus/CMakeLists.txt
  openage/convert/opus/__init__.pxd
  openage/convert/opus/opusenc.pyx
Labels: bugfix, buildsystem, python

#1064 Update Qt version requirement from 5.5 to 5.9
  doc/building.md
  libopenage/CMakeLists.txt
Labels: bugfix, buildsystem

#1070 convert: fix type error during opus conversion
  openage/convert/opus/opusenc.pyx
Labels: bugfix, python

#1069 Fix building placement
  copying.md
  libopenage/game_control.cpp
  libopenage/unit/producer.cpp
Labels: bugfix, c++, gamelogic, improvement
