Repository SFTtech/openage, pull requests merged in 2018-03, with the labels that each got.

#983 add actual formula from rev-eng for trade carts
  doc/reverse_engineering/game_mechanics/market.md
Labels: documentation, nice new thing ☺

#984 further details on trade gold
  doc/reverse_engineering/game_mechanics/market.md
Labels: documentation, improvement

#986 doc: fix python-jinja installation instructions for arch linux
  doc/build_instructions/arch_linux.md
Labels: bugfix, buildsystem, documentation

#988 readme: add money sink button
  README.md
Labels: documentation, nice new thing ☺
