Repository SFTtech/openage, pull requests merged in 2018-05, with the labels that each got.

#1012 buildsystem: clean up terminal output
  buildsystem/cythonize.py
  buildsystem/pxdgen.py
  openage/codegen/codegen.py
Labels: buildsystem, improvement, python

#1011 convert: fix asset path in standalone conversion
  openage/convert/main.py
  openage/game/main.py
Labels: assets, bugfix, python

#1013 gui: remove unsused lambda captures
  libopenage/gui/integration/private/gui_filled_texture_handles.cpp
Labels: c++, code quality

#1007 convert: use memoryviews in visgrep
  openage/convert/interface/visgrep.pyx
Labels: improvement, python

#1010 Update required Ubuntu version
  doc/build_instructions/debian.md
  doc/build_instructions/fedora.md
  doc/build_instructions/freebsd.md
  doc/build_instructions/opensuse_13.2.md
  doc/build_instructions/opensuse_tumbleweed.md
  doc/build_instructions/os_x_10.10_yosemite.md
  doc/build_instructions/ubuntu.md
  doc/building.md
Labels: bugfix, documentation

#1016 util: C++14ize constexpr functions
  libopenage/util/constexpr.h
Labels: c++, code quality

#1015 buildsystem: parallel cythonization
  buildsystem/cythonize.py
Labels: buildsystem, improvement

#1018 buildsystem: fix overly specific headerguard regex
  buildsystem/codecompliance/headerguards.py
Labels: bugfix, buildsystem, python

#1019 Add support for unpatched Age of Empires 2: The Conquerors
  copying.md
  openage/convert/driver.py
  openage/convert/game_versions.py
  openage/convert/main.py
Labels: assets, nice new thing ☺, python

#1023 This change allows the openage git repository checkout to be located in a directory that is a symlink
  buildsystem/check_py_file_list.py
  buildsystem/cythonize.py
  buildsystem/pxdgen.py
Labels: buildsystem, improvement
