Repository SFTtech/openage, pull requests merged in 2019-10, with the labels that each got.

#1163 Minor README improvements?
  README.md
Labels: bugfix, documentation

#1160 Packaging openage with prebuilt Qt
  CMakeLists.txt
  buildsystem/DetectProjectVersion.cmake
  buildsystem/scripts/EmbedWinDependencies.cmake
  buildsystem/scripts/copy_modules.py
  buildsystem/templates/ForwardVariables.cmake.in
  libopenage/config.cpp.in
  openage/config.py.in
  packaging/CMakeLists.txt
  packaging/CPackOptions.cmake
Labels: bugfix, buildsystem, improvement, packaging, windows

#1148 Enhanced singlefile conversion and support for DE1 formats
  doc/convert/convert_single_file.md
  doc/media/slp-files.md
  doc/media/smp-files.md
  openage/convert/CMakeLists.txt
  openage/convert/gamedata/unit.py
  openage/convert/hardcoded/texture.py
  openage/convert/singlefile.py
  openage/convert/slp.pyx
  openage/convert/slp_converter_pool.py
  openage/convert/smp.pyx
  openage/convert/texture.py
Labels: assets, nice new thing ☺, python

#1169 Adding .travis.yml for MacOSX-CI/Fix for CI-builds
  .travis.yml
  libopenage/CMakeLists.txt
Labels: buildsystem, mac os

#1173 Fix reading previous asset location
  openage/game/main.py
Labels: bugfix, python

#1176 Adding changes to docs from tests with CI for MacOSX
  doc/build_instructions/os_x_10.14_mojave.md
Labels: documentation, mac os

#1180 Updating build status badges
  README.md
Labels: documentation

#1179 Specify OpenGL (not OpenGLES) explicitly
  copying.md
  libopenage/gui/guisys/private/gui_application_impl.cpp
Labels: bugfix, c++, mac os, rendering, ui
