Repository SFTtech/openage, pull requests merged in 2019-11, with the labels that each got.

#1188 Adding favicon for webpages to assets
  assets/logo/favicon.ico
Labels: assets, nice new thing ☺

#832 Spelling
  README.md
  buildsystem/codecompliance/textfiles.py
  buildsystem/modules/FindOpusfile.cmake
  buildsystem/python.cmake
  doc/buildsystem.md
  doc/code/gui.md
  doc/code/testing.md
  doc/media/blendomatic.md
  libopenage/audio/dynamic_resource.h
  libopenage/audio/opus_dynamic_loader.cpp
  libopenage/audio/opus_in_memory_loader.cpp
  libopenage/audio/resource.h
  libopenage/audio/sound.h
  libopenage/engine.h
  libopenage/shader/program.cpp
  openage/config.py.in
Labels: documentation, improvement, python

#1194 CI: Changed travis.yml to internal package management
  .travis.yml
Labels: kevin, mac os

#1195 CI: Removing Travis, adding Github Workflow for MacOSX
  .github/workflows/macosx-ci.yml
  .travis.yml
Labels: kevin, mac os

#1182 Minimise state changes in renderer
  doc/code/renderer/README.md
  libopenage/renderer/CMakeLists.txt
  libopenage/renderer/opengl/CMakeLists.txt
  libopenage/renderer/opengl/render_pass.cpp
  libopenage/renderer/opengl/render_pass.h
  libopenage/renderer/opengl/renderer.cpp
  libopenage/renderer/opengl/renderer.h
  libopenage/renderer/renderer.cpp
  libopenage/renderer/renderer.h
  libopenage/renderer/tests.cpp
Labels: c++, rendering

#1193 SMX file support
  doc/convert/convert_single_file.md
  doc/media/smp-files.md
  doc/media/smx-files.md
  openage/convert/CMakeLists.txt
  openage/convert/singlefile.py
  openage/convert/slp.pyx
  openage/convert/smp.pyx
  openage/convert/smx.pyx
  openage/convert/texture.py
Labels: assets, documentation, improvement, python

#1200 Revised slp-files.md
  doc/media/slp-files.md
Labels: bugfix, documentation, improvement

#1202 Add "mod snapshots" idea to docs
  doc/ideas/gameplay.md
  doc/ideas/interface.md
  doc/ideas/technical.md
Labels: documentation
