Repository SFTtech/openage, pull requests merged in 2019-09, with the labels that each got.

#1143 Changelog
  changelog.md
  doc/changelogs/engine/v0.0.0.md
  doc/changelogs/engine/v0.1.0.md
  doc/changelogs/engine/v0.2.0.md
  doc/changelogs/engine/v0.2.1.md
  doc/changelogs/engine/v0.2.2.md
  doc/changelogs/engine/v0.2.3.md
  doc/changelogs/engine/v0.3.0-alpha.md
  doc/changelogs/engine/v0.3.0.md
  doc/changelogs/engine/v0.4.0.md
  doc/changelogs/nyan_api/v0.1.0.md
  doc/changelogs/nyan_api/v0.2.0.md
  doc/contributing.md
  doc/nyan/aoe2_nyan_tree.svg
  doc/nyan/aoe2_nyan_tree.uxf
  doc/nyan/api_reference/reference_ability.md
  doc/nyan/api_reference/reference_aux.md
  doc/releasing.md
Labels: documentation, nice new thing ☺

#1152 Updating easy tasks link in readme.md
  README.md
Labels: documentation

#1153 Changed issue label links in contributing.md
  copying.md
  doc/contributing.md
Labels: documentation

#1154 Gui improvements
  assets/qml/BindsHelp.qml
  assets/qml/IngameHud.qml
  buildsystem/codecompliance/__main__.py
  libopenage/engine.cpp
  libopenage/engine.h
  libopenage/game_control.cpp
  libopenage/game_control.h
  libopenage/gamestate/generator.cpp
  libopenage/gui/actions_list_model.cpp
  libopenage/gui/engine_link.cpp
  libopenage/gui/game_control_link.cpp
  libopenage/gui/game_control_link.h
  libopenage/renderer/color.cpp
  libopenage/renderer/color.h
  libopenage/unit/producer.cpp
  libopenage/unit/selection.cpp
  libopenage/unit/selection.h
  libopenage/unit/unit_type.h
  libopenage/util/fps.cpp
  libopenage/util/fps.h
  libopenage/util/profiler.cpp
  openage/convert/gamedata/unit.py
Labels: improvement, ui

#1158 Fixed typos and unreachable commands, indents, etc.
  buildsystem/modules/FindPython.cmake
  doc/ai/interface.md
  doc/build_instructions/gentoo.md
  doc/build_instructions/opensuse_13.2.md
  doc/code_style/mom.cpp
  doc/nyan/aoe2_nyan_tree.svg
  doc/nyan/aoe2_nyan_tree.uxf
  doc/nyan/api_reference/reference_ability.md
  doc/nyan/api_reference/reference_aux.md
  doc/nyan/api_reference/reference_modifier.md
  doc/nyan/api_reference/reference_root.md
  doc/reverse_engineering/networking/01-general.md
  doc/reverse_engineering/networking/03-sync.md
  doc/reverse_engineering/networking/04-lobby.md
  doc/reverse_engineering/networking/06-chat_message_spoofing.md
  doc/reverse_engineering/networking/07-primary_action.md
  doc/reverse_engineering/networking/08-movement.md
  doc/reverse_engineering/networking/09-formation.md
  doc/reverse_engineering/networking/10-unit_creation.md
  doc/reverse_engineering/networking/11-buildings.md
  doc/reverse_engineering/networking/13-other.md
  doc/reverse_engineering/networking/14-ai.md
  doc/reverse_engineering/networking/15-c-structs.md
  libopenage/console/buf.cpp
  libopenage/console/console.cpp
  libopenage/gui/category_contents_list_model.cpp
  libopenage/gui/guisys/link/gui_list_model.cpp
  libopenage/gui/guisys/private/gui_input_impl.cpp
  libopenage/gui/integration/public/gui_game_spec_image_provider.cpp
  libopenage/gui/resources_list_model.cpp
  libopenage/input/input_manager.cpp
  libopenage/options.cpp
  libopenage/pathfinding/a_star.cpp
  libopenage/renderer/font/font.cpp
  libopenage/terrain/terrain.cpp
  libopenage/terrain/terrain_object.cpp
  libopenage/texture.cpp
  libopenage/unit/ability.h
  libopenage/unit/action.cpp
  libopenage/unit/action.h
  libopenage/unit/unit.cpp
  libopenage/util/compress/bitstream.h
  libopenage/util/compress/lzxd.cpp
  openage/util/fslike/abstract.py
Labels: c++, documentation, improvement

#1161 Additions to docs for successful MacOSX build and Windows packaging, changes to top README.md
  README.md
  doc/build_instructions/os_x_10.10_yosemite.md
  doc/build_instructions/os_x_10.14_mojave.md
  doc/build_instructions/packages.md
  doc/build_instructions/windows_msvc.md
  doc/building.md
Labels: buildsystem, documentation, mac os, packaging, proposal, windows
