Repository SFTtech/openage, pull requests merged in 2019-05, with the labels that each got.

#1104 Updated linux building dependencies in building.md
  doc/building.md
Labels: buildsystem, documentation, improvement

#1101 [WIP] Technical overview for ideas/feature requests
  copying.md
  doc/ideas/ai.md
  doc/ideas/fr_technical_overview.md
  doc/ideas/gameplay.md
  doc/ideas/interface.md
Labels: documentation, nice new thing ☺

#1106 Fixed typo
  configure
  copying.md
Labels: bugfix, python

#1021 Modding API draft (data)
  doc/nyan/aoe2_nyan_tree.svg
  doc/nyan/aoe2_nyan_tree.uxf
  doc/nyan/nyan.md
  doc/nyan/openage-lib.md
Labels: api, big stuff, documentation, nice new thing ☺, nyan

#1103 Updating some code using C++17
  libopenage/coord/coord.h.template
  libopenage/datastructure/constexpr_map.h
  libopenage/datastructure/tests.cpp
Labels: c++, improvement

#1115 buildsystem: no transitive linkage for internally used libraries
  libopenage/CMakeLists.txt
Labels: buildsystem, improvement
