Repository SFTtech/openage, pull requests merged in 2019-12, with the labels that each got.

#1205 SMP damage modifier
  doc/media/smp-files.md
  doc/media/smx-files.md
  openage/convert/smp.pyx
  openage/convert/smx.pyx
Labels: assets, documentation, improvement

#1206 renderer: use shared_ptrs for renderer resources
  libopenage/renderer/CMakeLists.txt
  libopenage/renderer/opengl/CMakeLists.txt
  libopenage/renderer/opengl/buffer.cpp
  libopenage/renderer/opengl/buffer.h
  libopenage/renderer/opengl/context.cpp
  libopenage/renderer/opengl/context.h
  libopenage/renderer/opengl/framebuffer.cpp
  libopenage/renderer/opengl/framebuffer.h
  libopenage/renderer/opengl/geometry.cpp
  libopenage/renderer/opengl/geometry.h
  libopenage/renderer/opengl/render_pass.cpp
  libopenage/renderer/opengl/render_pass.h
  libopenage/renderer/opengl/render_target.cpp
  libopenage/renderer/opengl/render_target.h
  libopenage/renderer/opengl/renderer.cpp
  libopenage/renderer/opengl/renderer.h
  libopenage/renderer/opengl/shader.cpp
  libopenage/renderer/opengl/shader.h
  libopenage/renderer/opengl/shader_program.cpp
  libopenage/renderer/opengl/shader_program.h
  libopenage/renderer/opengl/simple_object.cpp
  libopenage/renderer/opengl/simple_object.h
  libopenage/renderer/opengl/texture.cpp
  libopenage/renderer/opengl/texture.h
  libopenage/renderer/opengl/texture_array.cpp
  libopenage/renderer/opengl/texture_array.h
  libopenage/renderer/opengl/uniform_input.cpp
  libopenage/renderer/opengl/uniform_input.h
  libopenage/renderer/opengl/vertex_array.cpp
  libopenage/renderer/opengl/vertex_array.h
  libopenage/renderer/opengl/window.cpp
  libopenage/renderer/opengl/window.h
  libopenage/renderer/renderer.cpp
  libopenage/renderer/renderer.h
  libopenage/renderer/shader_program.cpp
  libopenage/renderer/shader_program.h
  libopenage/renderer/tests.cpp
  libopenage/renderer/uniform_input.cpp
  libopenage/renderer/uniform_input.h
  libopenage/renderer/vulkan/windowvk.cpp
  libopenage/renderer/window.cpp
  libopenage/renderer/window.h
  libopenage/util/compiler.h
  libopenage/util/vector.h
Labels: c++, improvement, rendering

#1208 qt: don't define std::hash<QString> for qt >= 5.14
  libopenage/gui/guisys/private/livereload/gui_live_reloader.h
Labels: bugfix, c++, ui
