Repository SFTtech/openage, pull requests merged in 2020-12, with the labels that each got.

#1329 Reverse engineering: describe some specific SWGB mechanics [v2]
  doc/reverse_engineering/game_mechanics/swgb/power.md
  doc/reverse_engineering/game_mechanics/swgb/shields.md
  doc/reverse_engineering/game_mechanics/swgb/stealth.md
  doc/reverse_engineering/game_mechanics/swgb/ui-empire-nopower-detection.png
  doc/reverse_engineering/game_mechanics/swgb/ui-empire-shield-power.png
  doc/reverse_engineering/game_mechanics/swgb/ui-gungan-all-off-lq.png
  doc/reverse_engineering/game_mechanics/swgb/ui-gungan-all-off.png
  doc/reverse_engineering/game_mechanics/swgb/ui-gungan-stealth-detection-lq.png
  doc/reverse_engineering/game_mechanics/swgb/user-interface.md
Labels: assets, documentation, nice new thing ☺

#1347 change logo to svg and update domain names
  README.md
  doc/media/evolution-openage-gource.md
  doc/milestones.md
  openage/__init__.py
  packaging/CMakeLists.txt
Labels: documentation, improvement

#1346 Output summary of converter run for debugging
  .github/workflows/macosx-ci.yml
  doc/code/converter/README.md
  doc/code/converter/workflow.md
  doc/convert/debugger.md
  openage/convert/entity_object/conversion/aoc/genie_civ.py
  openage/convert/entity_object/conversion/aoc/genie_tech.py
  openage/convert/entity_object/conversion/aoc/genie_unit.py
  openage/convert/entity_object/conversion/ror/genie_tech.py
  openage/convert/main.py
  openage/convert/processor/conversion/aoc/processor.py
  openage/convert/processor/conversion/de2/processor.py
  openage/convert/processor/conversion/ror/processor.py
  openage/convert/processor/conversion/swgbcc/processor.py
  openage/convert/service/CMakeLists.txt
  openage/convert/service/debug_info.py
  openage/convert/tool/driver.py
  openage/convert/value_object/read/member_access.py
Labels: assets, nice new thing ☺, python, reporting
