Repository SFTtech/openage, pull requests merged in 2020-08, with the labels that each got.

#1282 Changelog v0.4.1
  doc/changelogs/engine/v0.4.1.md
Labels: documentation

#1283 Remove pillow from dependencies
  doc/build_instructions/arch_linux.md
  doc/build_instructions/debian.md
  doc/build_instructions/fedora.md
  doc/build_instructions/freebsd.md
  doc/build_instructions/opensuse_13.2.md
  doc/build_instructions/opensuse_tumbleweed.md
  doc/build_instructions/os_x_10.14_mojave.md
  doc/build_instructions/ubuntu.md
  doc/build_instructions/windows_msvc.md
  doc/building.md
  openage/__init__.py
Labels: documentation, improvement, packaging

#1291 Read number of SWGB blend modes from .dat file
  openage/convert/processor/conversion/aoc/processor.py
  openage/convert/tool/driver.py
  openage/convert/value_object/read/media/blendomatic.py
  openage/convert/value_object/read/media/datfile/empiresdat.py
Labels: assets, bugfix, python

#1301 Cython module library linking
  .mailmap
  CMakeLists.txt
  buildsystem/HandlePythonOptions.cmake
  buildsystem/modules/FindPython.cmake
  buildsystem/python.cmake
  buildsystem/templates/ForwardVariables.cmake.in
  copying.md
  openage/convert/service/export/opus/CMakeLists.txt
  openage/convert/service/export/png/CMakeLists.txt
Labels: buildsystem, improvement
