Repository SFTtech/openage, pull requests merged in 2020-09, with the labels that each got.

#1303 configure: support any compiler version suffix
  configure
Labels: buildsystem, improvement

#1304 buildsystem: prefer system's default python version
  CMakeLists.txt
  buildsystem/modules/FindPython.cmake
Labels: buildsystem, improvement

#1310 Add option for asset conversion without --force
  openage/convert/main.py
  openage/convert/service/init/conversion_required.py
  openage/convert/tool/subtool/acquire_sourcedir.py
  openage/game/main.py
Labels: assets, bugfix, improvement, python

#1309 Documentation overhaul for converter and gamestate development
  README.md
  doc/architecture.md
  doc/build_instructions/packages.md
  doc/contributing.md
  doc/convert/interactive.md
  doc/development.md
  doc/media/lzx_compression_info.md
  doc/media_convert.md
  doc/milestones.md
  doc/project_structure.md
  doc/releasing.md
  doc/status.md
  doc/troubleshooting.md
  openage_version
Labels: documentation, improvement

#1305 Fix some MSVC compiling issues
  libopenage/console/draw.cpp
  libopenage/rng/rng.cpp
Labels: bugfix, c++, windows

#1317 Sprite format specification
  doc/media/openage/sprite_format_spec.md
Labels: assets, documentation, rendering

#1319 Modpacks documentation
  doc/media/openage/modpack_definition_file.md
  doc/media/openage/modpacks.md
Labels: assets, documentation

#1321 doc: Update READMY.md with detailed informations about current project state
  README.md
Labels: documentation, improvement
