Repository SFTtech/openage, pull requests merged in 2020-10, with the labels that each got.

#1324 Add manifest file creator for a modpack
  copying.md
  openage/convert/entity_object/conversion/modpack.py
  openage/convert/entity_object/export/formats/CMakeLists.txt
  openage/convert/entity_object/export/formats/modpack_manifest.py
  openage/convert/processor/export/CMakeLists.txt
  openage/convert/processor/export/generate_manifest_hashes.py
  openage/convert/processor/export/modpack_exporter.py
Labels: assets, hacktoberfest, nice new thing ☺, python

#1325 Add sound support for single media export
  openage/convert/tool/singlefile.py
Labels: assets, nice new thing ☺, python

#1330 docs: fix casing typos
  doc/media/openage/modpack_definition_file.md
Labels: bugfix, documentation
