Repository SFTtech/openage, pull requests merged in 2020-11, with the labels that each got.

#1331 doc: Clarify 3rd bit in 'frame_type'
  doc/media/smx-files.md
Labels: assets, documentation

#1334 Fix pylint sanity checks for kevin builds
  buildsystem/codecompliance/__main__.py
  openage/cabextract/cab.py
  openage/convert/entity_object/conversion/aoc/genie_unit.py
  openage/convert/entity_object/conversion/converter_object.py
  openage/convert/value_object/read/media/drs.py
  openage/convert/value_object/read/media/pefile.py
  openage/convert/value_object/read/media/peresource.py
  openage/convert/value_object/read/media_types.py
  openage/convert/value_object/read/read_members.py
  openage/util/ordered_set.py
Labels: code quality, python

#1328 Create auxilary files for game edition/expansion information
  cfg/converter/games/game_editions.toml
  cfg/converter/games/game_expansions.toml
  cfg/converter/games/version-hashes/AFRI_KING.toml
  cfg/converter/games/version-hashes/AOC.toml
  cfg/converter/games/version-hashes/AOE1DE.toml
  cfg/converter/games/version-hashes/AOE2DE.toml
  cfg/converter/games/version-hashes/AOK.toml
  cfg/converter/games/version-hashes/HDEDITION.toml
  cfg/converter/games/version-hashes/ROR.toml
  cfg/converter/games/version-hashes/SWGB.toml
  cfg/converter/games/version-hashes/SWGB_CC.toml
  openage/convert/deprecated/struct_definition.py
  openage/convert/entity_object/conversion/genie_structure.py
  openage/convert/entity_object/export/media_export_request.py
  openage/convert/main.py
  openage/convert/service/conversion/internal_name_lookups.py
  openage/convert/service/init/mount_asset_dirs.py
  openage/convert/service/init/version_detect.py
  openage/convert/service/read/gamedata.py
  openage/convert/service/read/palette.py
  openage/convert/service/read/string_resource.py
  openage/convert/tool/driver.py
  openage/convert/tool/interactive.py
  openage/convert/tool/singlefile.py
  openage/convert/tool/subtool/version_select.py
  openage/convert/value_object/init/game_file_version.py
  openage/convert/value_object/init/game_version.py
  openage/convert/value_object/read/media/datfile/civ.py
  openage/convert/value_object/read/media/datfile/empiresdat.py
  openage/convert/value_object/read/media/datfile/graphic.py
  openage/convert/value_object/read/media/datfile/playercolor.py
  openage/convert/value_object/read/media/datfile/research.py
  openage/convert/value_object/read/media/datfile/sound.py
  openage/convert/value_object/read/media/datfile/tech.py
  openage/convert/value_object/read/media/datfile/terrain.py
  openage/convert/value_object/read/media/datfile/unit.py
  openage/convert/value_object/read/media/drs.py
  openage/game/main.py
Labels: assets, hacktoberfest, hacktoberfest-accepted, nice new thing ☺, python

#1336 SLP v4.2 export
  doc/build_instructions/arch_linux.md
  doc/build_instructions/debian.md
  doc/build_instructions/fedora.md
  doc/build_instructions/freebsd.md
  doc/build_instructions/opensuse_13.2.md
  doc/build_instructions/opensuse_tumbleweed.md
  doc/build_instructions/os_x_10.14_mojave.md
  doc/build_instructions/ubuntu.md
  doc/build_instructions/windows_msvc.md
  doc/building.md
  doc/media/slp-files.md
  openage/convert/value_object/read/media/slp.pyx
Labels: assets, python

#1327 set PNG compression optimization level via CLI
  openage/convert/entity_object/export/media_export_request.py
  openage/convert/entity_object/export/texture.py
  openage/convert/main.py
  openage/convert/processor/export/modpack_exporter.py
  openage/convert/tool/driver.py
  openage/convert/tool/singlefile.py
  openage/convert/value_object/read/media/blendomatic.py
Labels: assets, hacktoberfest, hacktoberfest-accepted, nice new thing ☺, python

#1296 update macOS ci config
  .github/workflows/macosx-ci.yml
  .gitignore
  CMakeLists.txt
  README.md
  doc/build_instructions/opensuse_13.2.md
  doc/build_instructions/opensuse_tumbleweed.md
  doc/build_instructions/os_x_10.14_mojave.md
Labels: bugfix, kevin
