Repository SFTtech/openage, pull requests merged in 2020-01, with the labels that each got.

#1210 SMP damage modifier formula update
  doc/media/images/damage_window_visualization.svg
  doc/media/smp-files.md
Labels: assets, documentation, improvement

#1211 Add 'make all' target
  Makefile
Labels: buildsystem, improvement, nice new thing ☺

#1203 Add CI config version to openage --version
  CMakeLists.txt
  openage/__init__.py
  openage/config.py.in
Labels: buildsystem, improvement, kevin
