Repository SFTtech/openage, pull requests merged in 2021-01, with the labels that each got.

#1352 Fix running the converter from './run' executable
  cfg/CMakeLists.txt
  openage/convert/main.py
  openage/game/main.py
Labels: assets, bugfix, python

#1356 Make generated nyan files more readable
  .github/workflows/macosx-ci.yml
  openage/convert/entity_object/export/formats/nyan_file.py
  openage/convert/main.py
  openage/convert/processor/conversion/aoc/modpack_subprocessor.py
  openage/convert/processor/conversion/aoc/pregen_processor.py
  openage/convert/processor/conversion/aoc/upgrade_ability_subprocessor.py
  openage/convert/processor/conversion/aoc/upgrade_attribute_subprocessor.py
  openage/convert/processor/conversion/de2/modpack_subprocessor.py
  openage/convert/processor/conversion/de2/tech_subprocessor.py
  openage/convert/processor/conversion/de2/upgrade_resource_subprocessor.py
  openage/convert/processor/conversion/ror/modpack_subprocessor.py
  openage/convert/processor/conversion/swgbcc/modpack_subprocessor.py
  openage/nyan/import_tree.py
  openage/nyan/nyan_structs.py
Labels: assets, code quality, python

#1358 Adapt ModpackInfo output to format version 1
  doc/media/openage/modpack_definition_file.md
  openage/convert/entity_object/conversion/modpack.py
  openage/convert/entity_object/export/formats/modpack_info.py
  openage/convert/processor/conversion/aoc/modpack_subprocessor.py
  openage/convert/processor/conversion/de2/modpack_subprocessor.py
  openage/convert/processor/conversion/ror/modpack_subprocessor.py
  openage/convert/processor/conversion/swgbcc/modpack_subprocessor.py
  openage/convert/processor/export/modpack_exporter.py
Labels: assets, python

#1359 Add more newly used DE2 resources (fixes DE2 conversion)
  openage/convert/processor/conversion/aoc/tech_subprocessor.py
  openage/convert/processor/conversion/aoc/upgrade_resource_subprocessor.py
  openage/convert/processor/conversion/de2/tech_subprocessor.py
  openage/convert/processor/conversion/de2/upgrade_resource_subprocessor.py
  openage/convert/service/debug_info.py
Labels: assets, bugfix, nyan, python

#1362 Typo fix
  .github/workflows/macosx-ci.yml
  copying.md
  doc/code/converter/architecture_overview.md
Labels: bugfix, documentation

#1364 add clang-format config which approximates our style
  .clang-format
  doc/code_style/mom.cpp
  doc/code_style/mom.h
Labels: code quality, nice new thing ☺

#1363 Speed up media conversion significantly
  cfg/converter/games/aoc/version_hashes.toml
  cfg/converter/games/aok/version_hashes.toml
  cfg/converter/games/de1/version_hashes.toml
  cfg/converter/games/de2/version_hashes.toml
  cfg/converter/games/game_editions.toml
  cfg/converter/games/game_expansions.toml
  cfg/converter/games/hd/version_hashes.toml
  cfg/converter/games/hd_ak/version_hashes.toml
  cfg/converter/games/ror/version_hashes.toml
  cfg/converter/games/swgb/version_hashes.toml
  cfg/converter/games/swgb_cc/version_hashes.toml
  openage/convert/entity_object/conversion/aoc/genie_object_container.py
  openage/convert/entity_object/export/CMakeLists.txt
  openage/convert/entity_object/export/data_definition.py
  openage/convert/entity_object/export/formats/CMakeLists.txt
  openage/convert/entity_object/export/formats/media_cache.py
  openage/convert/entity_object/export/media_export_request.py
  openage/convert/entity_object/export/metadata_export.py
  openage/convert/entity_object/export/texture.py
  openage/convert/main.py
  openage/convert/processor/conversion/aoc/media_subprocessor.py
  openage/convert/processor/conversion/aoc/modpack_subprocessor.py
  openage/convert/processor/conversion/de2/media_subprocessor.py
  openage/convert/processor/conversion/de2/modpack_subprocessor.py
  openage/convert/processor/conversion/de2/processor.py
  openage/convert/processor/conversion/ror/CMakeLists.txt
  openage/convert/processor/conversion/ror/media_subprocessor.py
  openage/convert/processor/conversion/ror/processor.py
  openage/convert/processor/export/CMakeLists.txt
  openage/convert/processor/export/__init__.pxd
  openage/convert/processor/export/data_exporter.py
  openage/convert/processor/export/generate_manifest_hashes.py
  openage/convert/processor/export/media_exporter.py
  openage/convert/processor/export/modpack_exporter.py
  openage/convert/processor/export/terrain_merge.pyx
  openage/convert/processor/export/texture_merge.py
  openage/convert/processor/export/texture_merge.pyx
  openage/convert/service/debug_info.py
  openage/convert/service/export/CMakeLists.txt
  openage/convert/service/export/load_media_cache.py
  openage/convert/service/export/png/CMakeLists.txt
  openage/convert/service/export/png/binpack.pyx
  openage/convert/service/export/png/png_create.pyx
  openage/convert/service/init/version_detect.py
  openage/convert/tool/driver.py
  openage/convert/tool/interactive.py
  openage/convert/tool/singlefile.py
  openage/convert/value_object/init/game_version.py
  openage/convert/value_object/read/media/colortable.py
  openage/convert/value_object/read/media/slp.pyx
  openage/convert/value_object/read/media/smp.pyx
  openage/convert/value_object/read/media/smx.pyx
  openage/nyan/import_tree.py
  openage/util/CMakeLists.txt
  openage/util/hash.py
Labels: assets, improvement, python

#1367 Fix: Turn Cython profiling off
  buildsystem/codecompliance/__main__.py
  buildsystem/codecompliance/cython.py
  openage/convert/processor/export/terrain_merge.pyx
  openage/convert/processor/export/texture_merge.pyx
  openage/convert/service/export/png/binpack.pyx
  openage/convert/service/export/png/png_create.pyx
  openage/convert/value_object/read/media/slp.pyx
  openage/convert/value_object/read/media/smp.pyx
  openage/convert/value_object/read/media/smx.pyx
Labels: bug, buildsystem, nice new thing ☺, python

#1368 Replace numpy.any() check with manual short-circuit check
  openage/convert/processor/export/terrain_merge.pyx
Labels: assets, improvement, python
