Repository SFTtech/openage, pull requests merged in 2021-08, with the labels that each got.

#1402 C++ 20 readiness
  CMakeLists.txt
  libopenage/util/constinit_vector.h
  libopenage/util/enum.h
Labels: improvement, buildsystem, c++

#1404 Cpp20 compliance
  libopenage/gui/guisys/link/gui_item.h
  libopenage/main/tests/gui.cpp
  libopenage/pyinterface/functional.h
  libopenage/unit/action.cpp
  libopenage/unit/producer.cpp
Labels: c++, code quality, bugfix

#1400 Fix the condition for pygments 2.10.0
  buildsystem/pxdgen.py
Labels: buildsystem, python, bugfix

#1398 Update copying.md year
  CMakeLists.txt
  README.md
  copying.md
  doc/development.md
  libopenage/gui/guisys/link/gui_item.h
  libopenage/main/tests/gui.cpp
  libopenage/pyinterface/functional.h
  libopenage/unit/action.cpp
Labels: documentation, bugfix

#1405 update documentation and buildsystem for C++20
  CMakeLists.txt
  README.md
  buildsystem/CheckCompilerFeatures.cmake
  doc/build_instructions/fedora.md
  doc/build_instructions/freebsd.md
  doc/build_instructions/macos.md
  doc/build_instructions/opensuse.md
  doc/build_instructions/opensuse_13.2.md
  doc/build_instructions/packages.md
  doc/build_instructions/ubuntu.md
  doc/building.md
  doc/ide/emacs.md
  doc/project_structure.md
Labels: improvement, buildsystem, documentation

#1406 Use C++ 20 spaceship operator
  libopenage/util/fixed_point.h
Labels: improvement, c++, code quality
