Repository SFTtech/openage, pull requests merged in 2021-09, with the labels that each got.

#1408 Fix Windows build failures
  libopenage/gui/guisys/public/gui_property_map.cpp
  libopenage/main/tests.cpp
  libopenage/main/tests.h
Labels: windows, buildsystem, bugfix

#1407 Suppress SDL_main definition
  buildsystem/modules/FindSDL2.cmake
  copying.md
  libopenage/CMakeLists.txt
Labels: buildsystem, bugfix

#1420 Fix check for handling unsupported versions
  openage/convert/tool/subtool/version_select.py
Labels: python, bugfix
