Repository SFTtech/openage, pull requests merged in 2023-10, with the labels that each got.

#1531 doc: Changelog v0.5.0
  doc/changelogs/engine/v0.5.0.md
Labels: documentation

#1560 Fix clang build
  libopenage/engine/engine.h
  libopenage/renderer/opengl/shader_program.cpp
Labels: area: renderer, area: simulation, bugfix

#1561 Make asset location cache file write more robust
  openage/convert/main.py
  openage/util/fslike/path.py
Labels: lang: python, area: assets, bugfix

#1563 Always handle asset path as `UnionPath`
  openage/assets.py
  openage/convert/main.py
  openage/convert/service/init/api_export_required.py
  openage/convert/service/init/conversion_required.py
  openage/convert/service/init/modpack_search.py
Labels: lang: python, area: assets, bugfix

#1565 Add missing asset directories to CMakeLists
  assets/test/CMakeLists.txt
  assets/test/nyan/CMakeLists.txt
  assets/test/qml/CMakeLists.txt
  libopenage/presenter/presenter.cpp
Labels: area: buildsystem, bugfix, lang: cmake

#1567 Changelog release `0.5.1`
  doc/changelogs/engine/v0.5.1.md
  openage_version
Labels: documentation

#1559 Fix an inappropriate test expression to remove a logical short circuit
  copying.md
  openage/convert/processor/conversion/aoc/processor.py
Labels: area: assets, bugfix

#1570 Fix out of bound access in matrix constructor
  libopenage/util/matrix.h
Labels: lang: c++, bugfix

#1575 Let `make run` call `main` sumodule instead of `game`
  Makefile
Labels: bugfix, area: launcher

#1576 Allow non-annotated tags from git for setting version
  buildsystem/DetectProjectVersion.cmake
Labels: area: buildsystem, bugfix

#1577 Check if clang jthread is joinable before joining
  libopenage/engine/engine.h
Labels: os: macos, lang: c++, bugfix

#1578 Prevent engine loop from being optimized out in release builds
  configure
  libopenage/engine/engine.cpp
Labels: area: buildsystem, bugfix

#1579 Modpack load fixes
  doc/media/openage/modpack_definition_file.md
  libopenage/gamestate/game.cpp
  openage/convert/tool/api_export.py
Labels: improvement, lang: c++, lang: python, bugfix

#1580 Add AUR instructions for installing `toml11`
  doc/build_instructions/arch_linux.md
Labels: improvement, documentation

#1582 Fix timestamp of video in README
  README.md
Labels: documentation, bugfix

#1581 Changelog release `0.5.2`
  doc/changelogs/engine/v0.5.1.md
  doc/changelogs/engine/v0.5.2.md
  openage_version
Labels: documentation

#1583 Fix version tag regex failure when HEAD is tagged
  buildsystem/DetectProjectVersion.cmake
Labels: area: buildsystem, bugfix

#1588 doc: Fix typos in converter
  doc/code/converter/architecture_overview.md
  doc/code/converter/workflow.md
Labels: improvement, documentation

#1589 Remove dangling refs in modpack info load
  libopenage/assets/modpack.cpp
Labels: lang: c++, area: assets, bugfix

#1590 Neutralize remaining instances of gendered language
  doc/ideas/gameplay.md
  doc/media/original-metadata.md
  doc/nyan/api_reference/reference_resistance.md
  doc/reverse_engineering/game_mechanics/formations.md
  doc/reverse_engineering/game_mechanics/monk_conversion.md
  doc/reverse_engineering/game_mechanics/selection.md
  doc/reverse_engineering/game_mechanics/switching_villager_tasks.md
  doc/reverse_engineering/game_mechanics/town_bell.md
  doc/reverse_engineering/game_mechanics/wolves.md
  doc/reverse_engineering/networking/02-header.md
  doc/reverse_engineering/networking/06-chat_message_spoofing.md
  doc/reverse_engineering/networking/08-movement.md
Labels: documentation

#1593 Fix typos
  openage/convert/entity_object/conversion/ror/genie_unit.py
Labels: documentation
