Repository SFTtech/openage, pull requests merged in 2023-12, with the labels that each got.

#1607 Add math constants corresbonding to `util/math_constants.h` for FixedPoint
  libopenage/util/fixed_point.h
  libopenage/util/fixed_point_test.cpp
Labels: nice new thing ☺, lang: c++

#1610 Add setuptools as conditionl dependency
  .github/workflows/macosx-ci.yml
  doc/building.md
Labels: area: buildsystem, bugfix

#1611 Changelog release 0.5.3
  .github/workflows/macosx-ci.yml
  doc/changelogs/engine/v0.5.3.md
  openage_version
Labels: documentation

#1613 Mention dependencies in changelog
  doc/changelogs/engine/v0.5.3.md
Labels: documentation

#1608 nyan data API v0.4.1
  doc/changelogs/nyan_api/v0.4.0.md
  doc/changelogs/nyan_api/v0.4.1.md
  doc/nyan/aoe2_nyan_tree.svg
  doc/nyan/aoe2_nyan_tree.uxf
  doc/nyan/api_reference/reference_ability.md
  doc/nyan/api_reference/reference_util.md
Labels: documentation, area: nyan, area: api
