Repository SFTtech/openage, pull requests merged in 2023-11, with the labels that each got.

#1591 Converter debug
  copying.md
  openage/convert/processor/export/media_exporter.py
  openage/convert/service/debug_info.py
  openage/convert/tool/driver.py
Labels: hacktoberfest-accepted

#1595 Fix append mode not available
  openage/util/fslike/path.py
  openage/util/fslike/union.py
Labels: lang: python, area: assets, bugfix

#1597 Check OpenGL format correctly on Wayland
  libopenage/renderer/opengl/context.cpp
Labels: os: linux, area: renderer, lang: c++, bugfix

#1598 Dynamically fetch default FBO
  libopenage/renderer/opengl/context.cpp
  libopenage/renderer/opengl/context.h
  libopenage/renderer/opengl/framebuffer.cpp
  libopenage/renderer/opengl/framebuffer.h
  libopenage/renderer/opengl/render_target.cpp
  libopenage/renderer/opengl/render_target.h
  libopenage/renderer/opengl/renderer.cpp
Labels: area: renderer, lang: c++, bugfix

#1587 Add `atan2` to `FixedPoint`
  copying.md
  libopenage/util/fixed_point.h
  libopenage/util/fixed_point_test.cpp
Labels: nice new thing ☺, lang: c++

#1600 Mirror anchor offset when flipping is active
  assets/shaders/world2d.vert.glsl
Labels: area: renderer, bugfix

#1599 PR templates
  .github/PULL_REQUEST_TEMPLATES/pull_request_template.md
  .github/PULL_REQUEST_TEMPLATES/release_template.md
Labels: nice new thing ☺, documentation

#1602 Use block indent for aligning after open brackets
  .clang-format
Labels: lang: c++, code quality

#1605 Revert "Merge pull request #1602 from heinezen/clang-format-align"
  .clang-format
Labels: code quality
