Repository SFTtech/openage, pull requests merged in 2024-07, with the labels that each got.

#1658 Make `util::constexpr_` consteval
  libopenage/log/message.h
  libopenage/util/consteval.h
Labels: improvement, lang: c++

#1647 nyan API v0.5.0
  doc/changelogs/nyan_api/v0.5.0.md
  doc/nyan/aoe2_nyan_tree.svg
  doc/nyan/aoe2_nyan_tree.uxf
  doc/nyan/api_reference/reference_ability.md
  doc/nyan/api_reference/reference_util.md
Labels: documentation, area: nyan

#1648 Update converter for nyan API v0.5.0
  openage/convert/entity_object/conversion/aoc/genie_object_container.py
  openage/convert/entity_object/conversion/aoc/genie_terrain.py
  openage/convert/processor/conversion/aoc/ability_subprocessor.py
  openage/convert/processor/conversion/aoc/modpack_subprocessor.py
  openage/convert/processor/conversion/aoc/nyan_subprocessor.py
  openage/convert/processor/conversion/aoc/pregen_processor.py
  openage/convert/processor/conversion/aoc/processor.py
  openage/convert/processor/conversion/de1/processor.py
  openage/convert/processor/conversion/de2/nyan_subprocessor.py
  openage/convert/processor/conversion/de2/processor.py
  openage/convert/processor/conversion/hd/processor.py
  openage/convert/processor/conversion/ror/nyan_subprocessor.py
  openage/convert/processor/conversion/ror/pregen_subprocessor.py
  openage/convert/processor/conversion/ror/processor.py
  openage/convert/processor/conversion/swgbcc/ability_subprocessor.py
  openage/convert/processor/conversion/swgbcc/nyan_subprocessor.py
  openage/convert/processor/conversion/swgbcc/pregen_subprocessor.py
  openage/convert/processor/conversion/swgbcc/processor.py
  openage/convert/service/init/api_export_required.py
  openage/convert/service/read/nyan_api_loader.py
  openage/convert/tool/api_export.py
  openage/convert/value_object/read/media/datfile/lookup_dicts.py
Labels: improvement, lang: python, area: assets

#1662 Frustum culling documentation
  assets/test/shaders/demo_6_2d_frame.frag.glsl
  assets/test/shaders/demo_6_2d_frustum_frame.vert.glsl
  doc/code/renderer/demos.md
  doc/code/renderer/images/demo_0.png
  doc/code/renderer/images/demo_1.png
  doc/code/renderer/images/demo_2.png
  doc/code/renderer/images/demo_3.png
  doc/code/renderer/images/demo_4.png
  doc/code/renderer/images/demo_5.png
  doc/code/renderer/images/demo_6.png
  doc/code/renderer/images/stresstest_0.png
  doc/code/renderer/images/stresstest_1.png
  doc/code/renderer/level2.md
  libopenage/renderer/camera/frustum_2d.cpp
  libopenage/renderer/camera/frustum_2d.h
  libopenage/renderer/demo/demo_6.cpp
  libopenage/renderer/demo/demo_6.h
Labels: area: renderer, lang: c++, documentation, bugfix

#1661 docs: Add note about linuxmint issue on ubuntu dependencies
  doc/build_instructions/ubuntu.md
Labels: os: linux, documentation

#1663 Fix DE2 conversion for 'The Mountain Royals' expansion
  openage/convert/processor/conversion/de2/modpack_subprocessor.py
  openage/convert/processor/conversion/de2/nyan_subprocessor.py
  openage/convert/processor/conversion/de2/processor.py
  openage/convert/processor/conversion/de2/tech_subprocessor.py
  openage/convert/processor/conversion/de2/upgrade_resource_subprocessor.py
  openage/convert/service/init/CMakeLists.txt
  openage/convert/service/init/api_export_required.py
  openage/convert/service/init/changelog.py
  openage/convert/service/init/modpack_search.py
  openage/convert/tool/driver.py
  openage/convert/value_object/conversion/de2/internal_nyan_names.py
  openage/convert/value_object/read/media/datfile/lookup_dicts.py
  openage/convert/value_object/read/media/datfile/unit.py
  openage/testing/testlist.py
Labels: lang: python, area: assets, bugfix
