Repository SFTtech/openage, pull requests merged in 2024-11, with the labels that each got.

#1702 Clang format rule: Indent preprocessor directives
  .clang-format
  libopenage/console/tests.cpp
  libopenage/engine/engine.h
  libopenage/error/handlers.cpp
  libopenage/error/stackanalyzer.cpp
  libopenage/event/demo/gui.cpp
  libopenage/event/demo/gui.h
  libopenage/event/demo/main.cpp
  libopenage/event/demo/physics.cpp
  libopenage/log/level.h
  libopenage/log/message.h
  libopenage/log/stdout_logsink.cpp
  libopenage/renderer/color.cpp
  libopenage/renderer/gui/guisys/private/opengl_debug_logger.cpp
  libopenage/renderer/vulkan/loader.cpp
  libopenage/util/compiler.cpp
  libopenage/util/fds.cpp
  libopenage/util/fds.h
  libopenage/util/fslike/directory.cpp
  libopenage/util/macro/concat.h
  libopenage/util/macro/loop.h
  libopenage/util/os.cpp
  libopenage/util/pty.h
  libopenage/util/strings.h
  libopenage/util/subprocess.cpp
  libopenage/util/thread_id.cpp
  libopenage/versions/versions.cpp
Labels: lang: c++, code quality

#1703 Make comparisons not ambiguous (fixes clang warnings)
  libopenage/coord/coord.h.template
Labels: lang: c++, code quality, bugfix

#1706 File system api c++: added support for creating temp. files and directories
  copying.md
  libopenage/util/file.cpp
  libopenage/util/file.h
  libopenage/util/fslike/directory.cpp
  libopenage/util/fslike/directory.h
  libopenage/util/path.cpp
  libopenage/util/path.h
Labels: improvement, nice new thing ☺, lang: c++, area: util

#1709 Fix definition of static functions for creating temp files/dirs
  libopenage/util/file.cpp
  libopenage/util/file.h
  libopenage/util/fslike/directory.cpp
Labels: bugfix, area: util

#1712 Convert Battle for Greece DLC
  openage/convert/processor/conversion/aoc/processor.py
  openage/convert/processor/conversion/de2/tech_subprocessor.py
  openage/convert/processor/conversion/de2/upgrade_attribute_subprocessor.py
  openage/convert/processor/conversion/de2/upgrade_resource_subprocessor.py
  openage/convert/value_object/conversion/de2/internal_nyan_names.py
  openage/convert/value_object/read/genie_structure.py
  openage/convert/value_object/read/media/datfile/lookup_dicts.py
Labels: improvement, nice new thing ☺, lang: python, area: assets

#1717 Changelog release 0.6.0
  doc/changelogs/engine/v0.6.0.md
  openage_version
Labels: documentation

#1720 pathfinding: small improvement
  libopenage/pathfinding/pathfinder.cpp
Labels: area: simulation
