Repository SFTtech/openage, pull requests merged in 2024-12, with the labels that each got.

#1721 Correct Typos
  doc/code/curves.md
Labels: documentation, bugfix

#1729 Upgrade Ubuntu docker file to 24.04
  .github/workflows/ubuntu-24.04.yml
  README.md
  packaging/docker/devenv/Dockerfile.ubuntu.2404
Labels: packaging, ci

#1731 change default entry sector value from null
  libopenage/pathfinding/pathfinder.cpp
  libopenage/pathfinding/pathfinder.h
Labels: lang: c++, area: simulation, bugfix

#1733 Update windows-server CI
  .github/workflows/windows-server-2019.yml
  .github/workflows/windows-server-2022.yml
Labels: bugfix, ci

#1723 Curve element wrapper
  libopenage/curve/CMakeLists.txt
  libopenage/curve/element_wrapper.cpp
  libopenage/curve/element_wrapper.h
  libopenage/curve/map.h
  libopenage/curve/map_filter_iterator.h
  libopenage/curve/queue.h
  libopenage/curve/queue_filter_iterator.h
Labels: improvement, lang: c++, area: util
